### ISSUE TITLE
[enhancement] Add taocpp.github.io on github project page

### ISSUE THREAD

**Issue by uilianries** [taocpp/taocpp.github.io#1]
Hi!

Just a small improvement, please add taocpp url on the github page:

![](https://screenshotscdn.firefoxusercontent.com/images/e1674b53-38de-4535-840f-3aa4cfc230ba.png)

As you can see, this will create a shortcut to access the web site.

**Comment by d-frey** [comment]
Fixed :)

**Comment by uilianries** [comment]
Thanks!
